# Use official Python image
FROM python:3.10


# Set working directory
WORKDIR /app


# Copy all files
COPY . .


# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt


# Expose the port Flask uses
EXPOSE 8080


# Run the app
CMD ["python", "app.py"]




